#!/bin/bash
module unload python

#Below loads the appropriate conda version
module load python

#Below will set the conda setting that adds an ugly environment name extension to the command prompt.
conda config --set changeps1 False

#Below will put you in a conda environment with ROOT 6.22 loaded.
source activate root-6.22.02


echo "ROOT and Python 3 Loaded"



#As if Sept. 2020 UChicago RCC has changed how they handle python.  
#This means the below are no longer the ideal options.  They are kept for now.
#module unload python
#module unload ROOT
#The below package of ROOT was built specifically for our purposes to support a recent build of python and ROOT.  It will load python 3.7.1.
#module load ROOT/6.16.00
#echo "ROOT/6.16.00 and Python 3.7.1 Loaded"
#Note that loading this module in a bashrc may cause issues if accessing midway2 with thinlinc.  The rcc guys couldn't really explain to me why, but I would recommend just loading it as you need it or finding a work around to a bashrc load.
